### ISSUE TITLE
Dam level as percentage

### ISSUE THREAD

**Issue by AlBrough** [bacco007/sensor.waternsw#1]
Hey Mate, 

Awesome work, thank you very much. How can I add the reading as a percentage rather than a value?
Please add a buy-me-a-beer link so I can sponsor you a few stubbies or some coffee!

**Comment by bacco007** [comment]
Hey!
I've added some of the variables most commonly seen on the dams to the Readme - https://github.com/bacco007/sensor.waternsw#dams---variables - this includes the percentage.   

Best to double-check on the WaterNSW site to see whether the From & To Variables are still the same for the dam you're interested in.
