### ISSUE TITLE
water nsw river levels

### ISSUE THREAD

**Issue by jackadoo800** [bacco007/sensor.waternsw#2]
great idea
 just wondering if this still works ?
I cant get any sort of reading just   entity not available
would love to use for monitoring river levels

thanks

**Comment by bacco007** [comment]
It should do - I just tried it with a random site (421001) - the variable required was 100

**Comment by jackadoo800** [comment]
thankyou 
I must be missing a step somewhere

**Comment by jackadoo800** [comment]
got it I had M  instead of Metres

**Comment by StormyKnight17** [comment]
Just worked out River Levels myself, I used "m" & it worked.
Any chance of updating the documentation to talk about river heights & perhaps an example?

```
- platform: waternsw
  name: Murrumbidgee Wagga
  site_id: 410001
  from_variable: 100
  to_variable: 100
  unit_of_measure: "m"
  
- platform: waternsw
  name: Murrumbidgee Gundagai
  site_id: 410004
  from_variable: 100
  to_variable: 100
  unit_of_measure: "m"
```
